name: CI - Web App Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build da imagem Docker
        run: docker compose build

      - name: Subir containers
        run: docker compose up -d

      - name: Aguardar aplicação subir
        run: |
          echo "Aguardando aplicação..."
          sleep 10

      - name: Executar testes automatizados
        run: ./scripts/test.sh

      - name: Derrubar containers
        if: always()
        run: docker compose down --volumes --remove-orphans
